// packages/web/src/layout/AppHeader.vue
<script setup lang="ts">
import {
  Bug,
  Menu,
  Moon,
  Palette,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRightClose,
  PanelRightOpen,
  Sun,
} from "lucide-vue-next";

defineProps<{
  theme: "dark" | "light";
  nextThemeLabel: "dark" | "light";
  sessionTitle: string;
  workspaceName: string | null;
  showDebugToggle: boolean;
  debugMode: boolean;
  debugModeLabel: string;
  sidebarCollapsed: boolean;
  showOutlineToggle: boolean;
  outlineSidebarOpen: boolean;
}>();

const emit = defineEmits<{
  toggleSidebar: [];
  toggleSidebarCollapse: [];
  toggleOutlineSidebar: [];
  toggleTheme: [];
  openThemeSettings: [];
  toggleDebugMode: [];
}>();
</script>

<template>
  <header class="app-header">
    <div class="header-leading">
      <button
        class="hamburger"
        aria-label="Toggle sidebar"
        @click="emit('toggleSidebar')"
      >
        <Menu class="hamburger-icon" aria-hidden="true" />
      </button>
      <button
        class="sidebar-collapse"
        type="button"
        :aria-label="
          sidebarCollapsed
            ? 'Expand sessions sidebar'
            : 'Collapse sessions sidebar'
        "
        :title="
          sidebarCollapsed
            ? 'Expand sessions sidebar'
            : 'Collapse sessions sidebar'
        "
        @click="emit('toggleSidebarCollapse')"
      >
        <PanelLeftOpen
          v-if="sidebarCollapsed"
          class="sidebar-collapse-icon"
          aria-hidden="true"
        />
        <PanelLeftClose
          v-else
          class="sidebar-collapse-icon"
          aria-hidden="true"
        />
      </button>
      <div class="header-brand">
        <p v-if="workspaceName" class="workspace-name">{{ workspaceName }}</p>
        <h1 class="app-title">{{ sessionTitle }}</h1>
      </div>
    </div>
    <div class="header-status">
      <button
        v-if="showOutlineToggle"
        class="outline-toggle"
        type="button"
        :aria-label="
          outlineSidebarOpen ? 'Collapse right sidebar' : 'Expand right sidebar'
        "
        :title="
          outlineSidebarOpen ? 'Collapse right sidebar' : 'Expand right sidebar'
        "
        @click="emit('toggleOutlineSidebar')"
      >
        <PanelRightClose
          v-if="outlineSidebarOpen"
          class="outline-toggle-icon"
          aria-hidden="true"
        />
        <PanelRightOpen v-else class="outline-toggle-icon" aria-hidden="true" />
      </button>
      <button
        v-if="showDebugToggle"
        class="debug-toggle"
        :class="{ active: debugMode }"
        type="button"
        :aria-label="debugModeLabel"
        :title="debugModeLabel"
        @click="emit('toggleDebugMode')"
      >
        <Bug class="debug-icon" aria-hidden="true" />
        <span class="debug-label">Debug</span>
      </button>
      <button
        class="appearance-toggle"
        type="button"
        aria-label="Open appearance settings"
        title="Open appearance settings"
        @click="emit('openThemeSettings')"
      >
        <Palette class="appearance-icon" aria-hidden="true" />
      </button>
      <button
        class="theme-toggle"
        type="button"
        :aria-label="`Switch to ${nextThemeLabel} theme`"
        :title="`Switch to ${nextThemeLabel} theme`"
        @click="emit('toggleTheme')"
      >
        <Sun v-if="theme === 'dark'" class="theme-icon" aria-hidden="true" />
        <Moon v-else class="theme-icon" aria-hidden="true" />
      </button>
    </div>
  </header>
</template>

<style scoped>
.app-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  height: 48px;
  padding: 0 16px;
  border-bottom: 1px solid var(--border);
  background: var(--bg-elevated);
  flex-shrink: 0;
  z-index: 20;
}

.header-leading {
  display: flex;
  align-items: center;
  gap: 12px;
  min-width: 0;
}

.hamburger {
  display: none;
  align-items: center;
  justify-content: center;
  width: 32px;
  height: 32px;
  padding: 0;
  background: none;
  border: none;
  color: var(--text-muted);
  cursor: pointer;
}

.hamburger-icon {
  width: 18px;
  height: 18px;
}

.header-brand {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  min-width: 0;
}

.workspace-name,
.app-title {
  margin: 0;
  max-width: min(100%, 48vw);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.workspace-name {
  font-size: 0.68rem;
  line-height: 1.1;
  font-weight: 600;
  letter-spacing: 0.03em;
  color: var(--text-subtle);
}

.app-title {
  font-size: 0.95rem;
  line-height: 1;
  font-weight: 600;
  letter-spacing: 0.01em;
  color: var(--text);
}

.header-status {
  display: flex;
  align-items: center;
  gap: 10px;
  flex-shrink: 0;
}

.sidebar-collapse,
.outline-toggle,
.debug-toggle,
.appearance-toggle,
.theme-toggle {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  height: 26px;
  padding: 0 10px;
  border-radius: 999px;
  border: 1px solid var(--border);
  background: var(--panel);
  font-size: 0.72rem;
  color: var(--text-subtle);
  cursor: pointer;
  transition:
    background 0.15s ease,
    border-color 0.15s ease,
    color 0.15s ease,
    transform 0.15s ease;
}

.debug-toggle {
  padding-right: 12px;
}

.sidebar-collapse:hover,
.outline-toggle:hover,
.debug-toggle:hover,
.appearance-toggle:hover,
.theme-toggle:hover {
  background: var(--surface-hover);
  border-color: var(--border-strong);
  color: var(--text-muted);
  transform: translateY(-1px);
}

.sidebar-collapse:focus-visible,
.outline-toggle:focus-visible,
.debug-toggle:focus-visible,
.appearance-toggle:focus-visible,
.theme-toggle:focus-visible {
  outline: none;
  border-color: var(--accent);
  box-shadow: 0 0 0 3px var(--focus-ring);
}

.debug-toggle.active {
  border-color: color-mix(in srgb, var(--accent) 36%, var(--border-strong));
  color: var(--text);
  background: var(--surface-active);
}

.sidebar-collapse,
.outline-toggle,
.appearance-toggle,
.theme-toggle {
  justify-content: center;
  width: 32px;
  height: 32px;
  padding: 0;
}

.sidebar-collapse-icon,
.outline-toggle-icon,
.debug-icon,
.appearance-icon,
.theme-icon {
  width: 16px;
  height: 16px;
}

@media (max-width: 900px) {
  .hamburger {
    display: flex;
  }

  .sidebar-collapse {
    display: none;
  }

  .app-header {
    height: auto;
    padding: calc(env(safe-area-inset-top) + 8px) 12px 10px;
  }

  .header-status {
    gap: 8px;
  }

  .debug-label {
    display: none;
  }

  .debug-toggle {
    padding-right: 10px;
  }
}

@media (max-width: 640px) {
  .app-header {
    padding-inline: 10px;
    gap: 10px;
  }

  .header-leading {
    gap: 10px;
  }

  .workspace-name,
  .app-title {
    max-width: min(100%, 42vw);
  }

  .hamburger,
  .outline-toggle,
  .appearance-toggle,
  .theme-toggle {
    width: 30px;
    height: 30px;
  }

  .debug-toggle {
    height: 28px;
    padding: 0 9px;
    font-size: 0.68rem;
  }
}
</style>

// packages/svelte/src/layout/AppHeader.svelte
<script lang="ts">
  import Bug from "lucide-svelte/icons/bug";
  import Menu from "lucide-svelte/icons/menu";
  import Moon from "lucide-svelte/icons/moon";
  import Palette from "lucide-svelte/icons/palette";
  import PanelLeftClose from "lucide-svelte/icons/panel-left-close";
  import PanelLeftOpen from "lucide-svelte/icons/panel-left-open";
  import PanelRightClose from "lucide-svelte/icons/panel-right-close";
  import PanelRightOpen from "lucide-svelte/icons/panel-right-open";
  import Sun from "lucide-svelte/icons/sun";
  import type { ThemeMode } from "../themes";

  let {
    theme,
    nextThemeLabel,
    sessionTitle,
    workspaceName,
    showDebugToggle = false,
    debugMode = false,
    debugModeLabel = "",
    sidebarCollapsed = false,
    showOutlineToggle = false,
    outlineSidebarOpen = false,
    onToggleSidebar = () => {},
    onToggleSidebarCollapse = () => {},
    onToggleOutlineSidebar = () => {},
    onToggleTheme = () => {},
    onOpenThemeSettings = () => {},
    onToggleDebugMode = () => {},
  }: {
    theme: "dark" | "light";
    nextThemeLabel: ThemeMode;
    sessionTitle: string;
    workspaceName: string | null;
    showDebugToggle?: boolean;
    debugMode?: boolean;
    debugModeLabel?: string;
    sidebarCollapsed?: boolean;
    showOutlineToggle?: boolean;
    outlineSidebarOpen?: boolean;
    onToggleSidebar?: () => void;
    onToggleSidebarCollapse?: () => void;
    onToggleOutlineSidebar?: () => void;
    onToggleTheme?: () => void;
    onOpenThemeSettings?: () => void;
    onToggleDebugMode?: () => void;
  } = $props();
</script>

<header class="app-header">
  <div class="header-leading">
    <button
      class="hamburger"
      aria-label="Toggle sidebar"
      onclick={onToggleSidebar}
    >
      <Menu aria-hidden="true" size={16} />
    </button>
    <button
      class="sidebar-collapse"
      type="button"
      aria-label={sidebarCollapsed
        ? "Expand sessions sidebar"
        : "Collapse sessions sidebar"}
      title={sidebarCollapsed
        ? "Expand sessions sidebar"
        : "Collapse sessions sidebar"}
      onclick={onToggleSidebarCollapse}
    >
      {#if sidebarCollapsed}
        <PanelLeftOpen aria-hidden="true" size={14} />
      {:else}
        <PanelLeftClose aria-hidden="true" size={14} />
      {/if}
    </button>
    <div class="header-brand">
      {#if workspaceName}
        <p class="workspace-name">{workspaceName}</p>
      {/if}
      <h1 class="app-title">{sessionTitle}</h1>
    </div>
  </div>
  <div class="header-status">
    {#if showOutlineToggle}
      <button
        class="outline-toggle"
        type="button"
        aria-label={outlineSidebarOpen
          ? "Collapse right sidebar"
          : "Expand right sidebar"}
        title={outlineSidebarOpen
          ? "Collapse right sidebar"
          : "Expand right sidebar"}
        onclick={onToggleOutlineSidebar}
      >
        {#if outlineSidebarOpen}
          <PanelRightClose aria-hidden="true" size={14} />
        {:else}
          <PanelRightOpen aria-hidden="true" size={14} />
        {/if}
      </button>
    {/if}
    {#if showDebugToggle}
      <button
        class="debug-toggle"
        class:active={debugMode}
        type="button"
        aria-label={debugModeLabel}
        title={debugModeLabel}
        onclick={onToggleDebugMode}
      >
        <Bug aria-hidden="true" size={14} />
        <span class="debug-label">Debug</span>
      </button>
    {/if}
    <button
      class="appearance-toggle"
      type="button"
      aria-label="Open appearance settings"
      title="Open appearance settings"
      onclick={onOpenThemeSettings}
    >
      <Palette aria-hidden="true" size={14} />
    </button>
    <button
      class="theme-toggle"
      type="button"
      aria-label={`Switch to ${nextThemeLabel} theme`}
      title={`Switch to ${nextThemeLabel} theme`}
      onclick={onToggleTheme}
    >
      {#if theme === "dark"}
        <Sun aria-hidden="true" size={14} />
      {:else}
        <Moon aria-hidden="true" size={14} />
      {/if}
    </button>
  </div>
</header>

<style>
  .app-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 12px;
    padding: 6px 8px 10px 8px;
    height: 44px;
    /*padding: 0 14px;*/
    border-bottom: 1px solid var(--border);
    border-top-left-radius: 14px;
    background: var(--bg);
    flex-shrink: 0;
    z-index: 20;
  }

  .header-leading {
    display: flex;
    align-items: center;
    gap: 10px;
    min-width: 0;
  }

  .hamburger {
    display: none;
    align-items: center;
    justify-content: center;
    width: 28px;
    height: 28px;
    padding: 0;
    background: none;
    border: none;
    color: var(--text-muted);
    cursor: pointer;
  }

  .header-brand {
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    min-width: 0;
  }

  .workspace-name,
  .app-title {
    margin: 0;
    max-width: min(100%, 48vw);
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .workspace-name {
    font-size: 0.64rem;
    line-height: 1.05;
    font-weight: 600;
    letter-spacing: 0.03em;
    color: var(--text-subtle);
  }

  .app-title {
    font-size: 0.9rem;
    line-height: 1;
    font-weight: 600;
    letter-spacing: 0.01em;
    color: var(--text);
  }

  .header-status {
    display: flex;
    align-items: center;
    gap: 4px;
    flex-shrink: 0;
  }

  .sidebar-collapse,
  .outline-toggle,
  .debug-toggle,
  .appearance-toggle,
  .theme-toggle {
    display: inline-flex;
    align-items: center;
    gap: 5px;
    height: 22px;
    width: 22px;
    flex: 0 0 22px;
    padding: 0 7px;
    border-radius: 6px;
    border: none;
    background: transparent;
    font-size: 0.68rem;
    color: var(--text-subtle);
    cursor: pointer;
    transition:
      background 0.15s ease,
      color 0.15s ease,
      transform 0.15s ease;
  }

  .debug-toggle {
    padding-right: 9px;
  }

  .sidebar-collapse:hover,
  .outline-toggle:hover,
  .debug-toggle:hover,
  .appearance-toggle:hover,
  .theme-toggle:hover {
    background: var(--surface-hover);
    color: var(--text-muted);
    transform: translateY(-1px);
  }

  .sidebar-collapse:focus-visible,
  .outline-toggle:focus-visible,
  .debug-toggle:focus-visible,
  .appearance-toggle:focus-visible,
  .theme-toggle:focus-visible {
    outline: none;
    box-shadow: 0 0 0 3px var(--focus-ring);
  }

  .debug-toggle.active {
    color: var(--text);
    background: var(--surface-active);
  }

  .sidebar-collapse {
    justify-content: center;
    width: 22px;
    height: 22px;
    padding: 0;
    flex: 0 0 22px;
  }

  .outline-toggle,
  .appearance-toggle,
  .theme-toggle {
    justify-content: center;
    width: 22px;
    height: 22px;
    padding: 0;
    flex: 0 0 22px;
  }

  @media (max-width: 900px) {
    .hamburger {
      display: flex;
    }

    .sidebar-collapse {
      display: none;
    }

    .app-header {
      height: auto;
      padding: calc(env(safe-area-inset-top) + 7px) 11px 9px;
      border-top-left-radius: 0;
    }

    .header-status {
      gap: 4px;
    }

    .debug-label {
      display: none;
    }

    .debug-toggle {
      padding-right: 7px;
    }
  }

  @media (max-width: 640px) {
    .app-header {
      padding-inline: 9px;
      gap: 8px;
    }

    .header-leading {
      gap: 8px;
    }

    .workspace-name,
    .app-title {
      max-width: min(100%, 42vw);
    }

    .hamburger {
      width: 24px;
      height: 24px;
    }

    .outline-toggle,
    .appearance-toggle,
    .theme-toggle {
      width: 22px;
      height: 22px;
      flex: 0 0 22px;
    }

    .debug-toggle {
      height: 24px;
      padding: 0 7px;
      font-size: 0.66rem;
    }
  }
</style>
